### PR TITLE
Multiple candlestick events on single websocket connection

### PR DESCRIPTION
**Pull request by alicanalbayrak**
Binance provides to access multiple symbols at single websocket connection by combining stream names.

> Combined streams are accessed at `/stream?streams<streamName1>/<streamName2>/<streamName3>`

Here, I added trivial method to listen candlestick events on multiple symbols.

### CODE REVIEW

**Comment by mcourteaux** [comment]
Have you actually tested this? Because the documentation states that you need to use 

 > * Combined streams are accessed at `/stream?streams=<streamName1>/<streamName2>/<streamName3>`

Whereas you seem to be using this:

    public static final String WS_API_BASE_URL = "wss://stream.binance.com:9443/ws";

The documentation also states that the combined streams are wrapped:

> Combined stream events are wrapped as follows: `{"stream":"<streamName>","data":<rawPayload>}`

You also don't seem to do any unwrapping. I'd be surprised if your proposed changes would work, given that they are so non-conform the documentation.

**Comment by alicanalbayrak** [comment]
I'm suprised too, I have tested and its working. You are right, I wasn't aware that I'm using this "wss://stream.binance.com:9443/ws"; endpoint.

**Comment by alicanalbayrak** [comment]
@mcourteaux I have added methods to consume (aggregated trade, depth and candlestick events ) from  `"wss://stream.binance.com:9443/stream?streams="`

**Comment by mcourteaux** [comment]
I'll review your changes soon. We also implemented working combined streams. I'll compare your changes to ours. Still working on something else now.

**Comment by joaopsilva** [comment]
Hi @alicanalbayrak , thanks for your contribution, could you please resolve the conflicts?

**Comment by alicanalbayrak** [comment]
Hi @joaopsilva , sorry for the late reply. I resolved conflicting files. Can you please review.

**Comment by hsinhunglee** [comment]
Hi, it looks doesn't work. I find the bug at
main.java.com.binance.api.client.impl/BinanceApiWebSocketClientImpl.java
correct:
`String streamingUrl = String.format("%s%s", streamUrl, channel);`
wrong:
`String streamingUrl = String.format("%s/%s", streamUrl, channel);`
I corrected it, then it work!

**Comment by Gilianp** [comment]
As mensioned by @hsinhunglee, when remove "/" from format the problem is fixed :)

**Comment by joaopsilva** [comment]
Fixed in https://github.com/binance-exchange/binance-java-api/pull/178.

**Pull request closed without merging**
