### PR TITLE
Implementation of OCO orders

### PR DESCRIPTION
**Pull request by yaniferhaoui**
Implemented and tested in real conditions

### CODE REVIEW

**Comment by hoeckxer** [comment]
This merge request would be very welcome!!!

**Comment by mogorschampion** [comment]
tested, works well

**Review by joaopsilva — APPROVED** [review]
lgtm, well done, thanks!

**Comment by alierturk122** [comment]
Hello,

There is a new announcement for OCO orders support on the margin account. Is there any implementation or plan to add this to the library? Thank you.


**2021-08-23**

> New endpoints for Margin Account OCO:
- > POST /sapi/v1/margin/order/oco
- > DELETE /sapi/v1/margin/orderList
- > GET /sapi/v1/margin/orderList
- > GET /sapi/v1/margin/allOrderList
- > GET /sapi/v1/margin/openOrderList

Same usage as spot account OCO

**Pull request merged**
