### PR TITLE
fixes #74 - use project lombok to cut down boilerplate in domain models

### LINKED ISSUE #74: reduce boilerplate by using project lombok
The domain models contain an awful lot of boilerplate code that can be reduced to one-liners in many cases with the aid of project lombok. see https://projectlombok.org.

### PR DESCRIPTION
**Pull request by olee87**
The title says it all - make use of https://projectlombok.org to remove most of the boilerplate code in domain model classes

### CODE REVIEW

**Comment by joaopsilva** [comment]
Hi @olee87 , thanks for this. Would there be a way to customize the `ToString` method with Lombok?

**Comment by olee87** [comment]
Absolutely! It can be as simple as overriding it wherever you need. or you make of the [`@ToString `](https://projectlombok.org/features/ToString) annotation explicitly rather than implicitly through the `@Data` annotation

**Comment by olee87** [comment]
I updated the PR to go back to the explicit toString methods so they remain configurable.

**Comment by olee87** [comment]
Also, as a heads-up: incorporating this will mean that you have to use a lombok-plugin in your IDE to trigger bytecode generation. It is ridiculously easy to install in both IntelliJ and Eclipse, though.

**Comment by big-andy-coates** [comment]
Rather a library that requires bytecode generation, (which I for one wouldn't be willing to install or trust), why not just rework the PoJo's to be immutable, talking all params in the constructor? That removes the need for the setter. Then, if you really want to cut down code, just make the immutable fields public.

**Comment by joaopsilva** [comment]
Hi @olee87 , I have to agree with @big-andy-coates here, although I like project-lombok, I believe it's a bit overkill for this library, since most folks won't really be digging into the domain classes that often.

Hopefully, Data classes arrive to Java soon enough (http://cr.openjdk.java.net/~briangoetz/amber/datum.html), in a similar way that they exist already for Kotlin.

Thanks again for your contribution.

**Pull request closed without merging**
