### PR TITLE
Fix non-existent 'outboundAccountInfo' event. Replaced by 'outboundAccountPosition'.

### PR DESCRIPTION
**Pull request by mcourteaux**
This fixes: #355, and probably #309.

This will cause people using this non-existent thing to cause compilation problems, which in my opinion is exactly what you want: the compiler telling you that your trading logic is using some non-existent thing in the API. Backwards compatibility is really not what you want here IMO. Updating this repository should indeed force you to look into your bug.

### CODE REVIEW

**Comment by joaopsilva** [comment]
Thanks.

**Comment by brintal** [comment]
But UserDataUpdateEventType.ACCOUNT_UPDATE is still used in the example included in the project. Hence the maven build is breaking now?!

**Comment by mcourteaux** [comment]
> But UserDataUpdateEventType.ACCOUNT_UPDATE is still used in the example included in the project. Hence the maven build is breaking now?!

I updated the tests, and the Maven build is working for me. I looked through the code, and it seems here indeed:
https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/UserDataStreamExample.java#L30
it is still used. This is not reported when I did `mvn install`. How do you trigger the error?

**Comment by brintal** [comment]
@mcourteaux 
Could you try executing `mvn clean install`. It seems like you still have the old classes in your classpath hence no error for you.
I just cloned the repo on a new machine and just did `mvn clean install`. Result:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/michael/Dev/IdeaProjects/binance-java-api/src/test/java/com/binance/api/examples/AccountBalanceCacheExample.java:[12,1] cannot find symbol
  symbol:   static ACCOUNT_UPDATE
  location: class
[ERROR] /home/michael/Dev/IdeaProjects/binance-java-api/src/test/java/com/binance/api/examples/UserDataStreamExample.java:[30,61] cannot find symbol
  symbol:   variable ACCOUNT_UPDATE
  location: class com.binance.api.client.domain.event.UserDataUpdateEvent.UserDataUpdateEventType
[ERROR] /home/michael/Dev/IdeaProjects/binance-java-api/src/test/java/com/binance/api/examples/MarginUserDataStreamExample.java:[31,61] cannot find symbol
  symbol:   variable ACCOUNT_UPDATE
  location: class com.binance.api.client.domain.event.UserDataUpdateEvent.UserDataUpdateEventType
[ERROR] /home/michael/Dev/IdeaProjects/binance-java-api/src/test/java/com/binance/api/examples/AccountBalanceCacheExample.java:[61,38] cannot find symbol
  symbol:   variable ACCOUNT_UPDATE
  location: class com.binance.api.examples.AccountBalanceCacheExample

```

**Comment by mcourteaux** [comment]
@brintal I made followup PR to fix examples: https://github.com/binance-exchange/binance-java-api/pull/388

**Pull request merged**
