### PR TITLE
Transfer/borrow/repay margin endpoints

### PR DESCRIPTION
**Pull request by truonghatsts**
Contains #240 #225 

Add extra 3 endpoints for transfer, borrow, repay

### CODE REVIEW

**Comment by bacsog** [comment]
Please?

**Comment by fenixgobear** [comment]
I got the issue when borrowing today while it runs properly before.
`com.binance.api.client.exception.BinanceApiException: Please make sure there is enough balance in your wallet.`

Anyone got the same issue?

**Comment by taylancapraz** [comment]
Any update to this?

**Comment by taylancapraz** [comment]
@truonghatsts hi,
Will you continue this task?

**Comment by truonghatsts** [comment]
@taylancapraz Let me clean up the codebase and put it back.

**Comment by Denebulas** [comment]
Hello 
is it now possible to call the borrow functions ?
Thanx

**Comment by truonghatsts** [comment]
@taylancapraz Just cleaned up the codebase and make the PR for it https://github.com/binance-exchange/binance-java-api/pull/283

**Pull request closed without merging**
